wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1673655674.315427
    t:
      1:
      - 1
      - 40
      - 49
      - 51
      - 55
      2:
      - 1
      - 40
      - 49
      - 51
      - 55
      3:
      - 2
      - 23
      4: 3.10.8
      5: 0.13.9
      8:
      - 1
      - 4
      - 5
